#!/usr/bin/env python3

import json
import locale
import os
import emails
import sys
from reportlab.platypus import SimpleDocTemplate
from reportlab.platypus import Paragraph, Table
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors


def load_data(filename):
    """Loads the contents of filename as a JSON file."""
    with open(filename) as json_file:
        data = json.load(json_file)
    return data


def format_car(car):
    """Given a car dictionary, returns a nicely formatted name."""
    car_make = car["car_make"]
    car_model = car["car_model"]
    car_year = car["car_year"]
    # print(f"{car_make} {car_model}, ({car_year})")
    return f"{car_make} {car_model}, ({car_year})"
    # return ("{} {} ({})").format(
    #     car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
    """Analyzes the data, looking for maximums.

    Returns a list of lines that summarize the information."""
    max_revenue = {"revenue": 0}
    popular_models = {}
    popular_year_sale = {}
    for item in data:
        # Calculate the revenue generated by this model (price * total_sales)
        # We need to convert the price from "$1234.56" to 1234.56
        item_price = locale.atof(item["price"].strip("$"))
        item_revenue = item["total_sales"] * item_price
        if item_revenue > max_revenue["revenue"]:
            item["revenue"] = item_revenue
            max_revenue = item

        # TODO: also handle max sales
        model_name = item["car"]["car_model"]
        model_quantity_sold = item["total_sales"]
        if model_name in popular_models.keys():
            popular_models[model_name] += model_quantity_sold
        else:
            popular_models[model_name] = model_quantity_sold

        # TODO: also handle most popular car_year

        car_year = item["car"]["car_year"]
        if car_year in popular_year_sale:
            popular_year_sale[car_year] += item["total_sales"]
        else:
            popular_year_sale[car_year] = item["total_sales"]

    sorted_popular_models = sorted(popular_models.items(), key=lambda x: x[1], reverse=True)
    sorted_popular_years = sorted(popular_year_sale.items(), key=lambda x: x[1], reverse=True)

    most_popular_model = sorted_popular_models[0][0]
    most_popular_model_quantity = sorted_popular_models[0][1]
    most_popular_year = sorted_popular_years[0][0]
    most_popular_year_quantity = sorted_popular_years[0][1]

    # summary = f"The {format_car(max_revenue['car'])} generated the most revenue: ${max_revenue['revenue']}."\
    #           f" The {most_popular_model} had the most sales: {most_popular_model_quantity}."\
    #           f" The most popular year was {most_popular_year} with {most_popular_year_quantity} sales."
    summary = "The {} generated the most revenue: ${}".format(
        format_car(max_revenue["car"]), max_revenue["revenue"]),\
        "The {} had the most sales: {}".format(
            sorted_popular_models[0][0], sorted_popular_models[0][1]),\
        "The most popular year was {} with {} sales.".format(
            sorted_popular_years[0][0], sorted_popular_years[0][1])
    return summary


def cars_dict_to_table(car_data):
    """Turns the data in car_data into a list of lists."""
    table_data = [["ID", "Car", "Price", "Total Sales"]]
    for item in car_data:
        table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
    return table_data


def main(argv):
    """Process the JSON data and generate a full report out of it."""
    data = load_data("car_sales.json")
    summary = process_data(data)
    # TODO: turn this into a PDF report
    report = SimpleDocTemplate("cars.pdf")
    styles = getSampleStyleSheet()
    report_title = Paragraph("Cars: summary", styles["h1"])
    table_data = cars_dict_to_table(data)
    table_style = [('GRID', (0, 0), (-1, -1), 1, colors.black)]
    report_body = Paragraph("<br/>".join(summary), styles["Normal"])
    report_table = Table(data=table_data, style=table_style, hAlign="LEFT")
    report.build([report_title, report_body, report_table])


    # TODO: send the PDF report as an email attachment
    sender = "automation@example.com"
    recipient = "{}@example.com".format(os.environ.get('USER'))
    subject = "Sales summary for last month"
    body = "\n".join(summary)
    attachment_path = "cars.pdf"
    message = emails.generate(sender, recipient, subject, body, attachment_path)
    emails.send(message)

if __name__ == "__main__":
    main(sys.argv)
